# Generated by Django 5.1.4 on 2025-06-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('experiencia', models.PositiveIntegerField(help_text='años de experiencia')),
            ],
        ),
        migrations.CreateModel(
            name='Zonaturistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='api.guia')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='api.zonaturistica')),
            ],
        ),
    ]
