# Generated by Django 5.1.4 on 2025-06-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='experiencia',
        ),
        migrations.AddField(
            model_name='guia',
            name='idioma',
            field=models.CharField(default='Español', max_length=50),
            preserve_default=False,
        ),
    ]
